#!/usr/bin/env python3
"""
===============================================================================
Script: train_yolo.py
Project: Packera dubia Species Delimitation & Morphometrics Pipeline

Description:
    Trains an Ultralytics YOLO instance segmentation model (e.g., YOLO11-seg)
    using the dataset generated by the SAM 2 botanical annotator.
    Configured for local GPU execution.
===============================================================================
"""

import argparse
import logging
from pathlib import Path
import yaml
import sys

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("TrainYOLO")

def generate_dataset_yaml(yolo_dir: Path) -> Path:
    """Generates the dataset.yaml file required by Ultralytics if it does not exist."""
    dataset_yaml_path = yolo_dir / "dataset.yaml"
    
    # Class definitions based on SAM 2 annotator mapping
    classes = [
        "basal_leaf_whole",
        "basal_leaf_partial",
        "cauline_leaf",
        "cauline_stem",
        "root_rhizome",
        "basal_rosette_clump",
        "capitulum"
    ]
    
    yaml_data = {
        "path": str(yolo_dir.resolve()), # dataset root dir
        "train": "images/train",         # train images (relative to 'path')
        "val": "images/val",             # val images (relative to 'path')
        "test": "images/test",           # test images (optional)
        "names": {i: name for i, name in enumerate(classes)}
    }
    
    # Write to file
    with open(dataset_yaml_path, 'w') as f:
        yaml.dump(yaml_data, f, default_flow_style=False)
        
    logger.info(f"Generated dataset config at {dataset_yaml_path}")
    return dataset_yaml_path

def main():
    parser = argparse.ArgumentParser(description="Train Ultralytics YOLO segmentation model.")
    parser.add_argument("--model", type=str, default="yolo11n-seg.pt", help="Pretrained YOLO model to start from.")
    parser.add_argument("--epochs", type=int, default=100, help="Number of training epochs.")
    parser.add_argument("--batch-size", type=int, default=16, help="Batch size (reduce if you run out of VRAM).")
    parser.add_argument("--img-size", type=int, default=1024, help="Image size for training (herbarium sheets are high-res).")
    parser.add_argument("--dataset-dir", type=str, default="data/yolo_dataset", help="Path to YOLO dataset directory.")
    args = parser.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("The 'ultralytics' package is not installed. Please run: pip install ultralytics")
        sys.exit(1)

    yolo_dir = PROJECT_ROOT / args.dataset_dir
    if not yolo_dir.exists():
        logger.warning(f"Dataset directory {yolo_dir} does not exist. Ensure SAM 2 annotations are exported.")
        yolo_dir.mkdir(parents=True, exist_ok=True)
        (yolo_dir / "images" / "train").mkdir(parents=True, exist_ok=True)
        (yolo_dir / "images" / "val").mkdir(parents=True, exist_ok=True)
        (yolo_dir / "labels" / "train").mkdir(parents=True, exist_ok=True)
        (yolo_dir / "labels" / "val").mkdir(parents=True, exist_ok=True)
    
    yaml_path = yolo_dir / "dataset.yaml"
    if not yaml_path.exists():
        yaml_path = generate_dataset_yaml(yolo_dir)
        
    logger.info(f"Initializing model {args.model}...")
    model = YOLO(args.model)
    
    logger.info(f"Starting training for {args.epochs} epochs with batch size {args.batch_size}...")
    
    # Train the model
    # Note: 'device=0' is used for local GPU training
    results = model.train(
        data=str(yaml_path),
        epochs=args.epochs,
        imgsz=args.img_size,
        batch=args.batch_size,
        device=0, 
        project=str(PROJECT_ROOT / "models" / "yolo_train_output"),
        name="packera_seg_model",
        exist_ok=True,
        # Herbarium sheets are fairly static, but these augmentations help
        fliplr=0.5,
        flipud=0.0, # Do not flip up-down because sheets have a distinct vertical orientation
        mosaic=1.0, 
        degrees=10.0, # Slight rotation
    )
    
    logger.info("Training complete.")
    logger.info(f"Best model saved to: {PROJECT_ROOT / 'models' / 'yolo_train_output' / 'packera_seg_model' / 'weights' / 'best.pt'}")

if __name__ == "__main__":
    main()
