import numpy as np
from dataclasses import dataclass, field, asdict
from typing import List, Tuple, Dict, Optional, Any

from scripts.core.config import CLASS_NAMES

@dataclass
class ArtifactDetection:
    """
    Represents a detected layout artifact bounding region on a herbarium sheet.
    
    Attributes:
        box: Bounding box [xmin, ymin, xmax, ymax] in absolute integer pixel coordinates.
        category: Label category (e.g., 'herbarium_label', 'color_chart', 'ruler_scale',
                  'barcode_sticker', 'institution_stamp', 'mounting_tape').
        confidence: Confidence score of the detection in range [0.0, 1.0].
        polygon: Optional list of polygon vertex coordinates [[x1, y1], [x2, y2], ...].
        metadata: Optional dictionary containing additional detector telemetry.
    """
    box: List[int]
    category: str
    confidence: float = 1.0
    polygon: Optional[List[List[int]]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class GeometricMetrics:
    """
    Mathematical morphological parameters extracted from a candidate mask.
    """
    mask_area: float
    min_area_rect_area: float
    rectangularity: float
    convex_hull_area: float
    solidity: float
    num_approx_vertices: int
    corner_angles_deg: List[float]
    is_rectangular: bool
    is_orthogonal_quad: bool
    is_valid_solidity: bool

@dataclass
class SpectralMetrics:
    """
    Colorimetric and HSV spectral distribution metrics.
    """
    mean_hue: float
    mean_saturation: float
    mean_value: float
    high_saturation_pixel_count: int
    high_saturation_ratio: float
    is_color_swatch: bool

@dataclass
class TextureMetrics:
    """
    High-frequency texture, gradient variance, and typographic stroke metrics.
    """
    laplacian_variance: float
    canny_edge_density: float
    horizontal_stroke_density: float
    vertical_stroke_density: float
    is_printed_text: bool

@dataclass
class FilterResult:
    """
    Comprehensive diagnostic output generated by the validation gatekeeper.
    """
    is_valid: bool
    status: str
    primary_rejection_reason: Optional[str]
    reclassified_category: Optional[str]
    geometric_metrics: GeometricMetrics
    spectral_metrics: SpectralMetrics
    texture_metrics: TextureMetrics
    routed_file_path: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert dataclass hierarchy to a JSON-serializable dictionary."""
        return asdict(self)

class InstanceAnnotation:
    """
    Represents a single segmented instance on a herbarium sheet.
    Stores class ID, normalized/absolute bounding box, and polygon contour points.
    """
    def __init__(
        self,
        class_id: int,
        polygon: np.ndarray,  # Shape (N, 2) in absolute pixel coordinates [[x, y], ...]
        bbox: Optional[Tuple[float, float, float, float]] = None,  # (x1, y1, x2, y2)
        confidence: float = 1.0,
        is_synthetic: bool = False,
        tag: str = ""
    ):
        self.class_id = int(class_id)
        self.polygon = np.asarray(polygon, dtype=np.float32)
        if bbox is not None:
            self.bbox = (float(bbox[0]), float(bbox[1]), float(bbox[2]), float(bbox[3]))
        else:
            if len(self.polygon) > 0:
                x_min = float(np.min(self.polygon[:, 0]))
                y_min = float(np.min(self.polygon[:, 1]))
                x_max = float(np.max(self.polygon[:, 0]))
                y_max = float(np.max(self.polygon[:, 1]))
                self.bbox = (x_min, y_min, x_max, y_max)
            else:
                self.bbox = (0.0, 0.0, 0.0, 0.0)
        self.confidence = float(confidence)
        self.is_synthetic = bool(is_synthetic)
        self.tag = tag

    @property
    def class_name(self) -> str:
        if 0 <= self.class_id < len(CLASS_NAMES):
            return CLASS_NAMES[self.class_id]
        return f"class_{self.class_id}"

    def to_yolo_seg_line(self, img_w: int, img_h: int) -> str:
        """
        Converts instance polygon to Ultralytics YOLO segmentation format:
        <class_id> <x1_norm> <y1_norm> <x2_norm> <y2_norm> ...
        """
        if len(self.polygon) < 3 or img_w <= 0 or img_h <= 0:
            return ""
        norm_poly = self.polygon.copy()
        norm_poly[:, 0] /= img_w
        norm_poly[:, 1] /= img_h
        norm_poly = np.clip(norm_poly, 0.0, 1.0)
        poly_str = " ".join([f"{x:.6f} {y:.6f}" for x, y in norm_poly])
        return f"{self.class_id} {poly_str}"
