#!/usr/bin/env python3
"""
===============================================================================
Script: train_lm2_pointrend.py
Project: Packera dubia Species Delimitation & Morphometrics Pipeline
Affiliation: University of North Carolina at Chapel Hill Herbarium (NCU)

Description:
    PyTorch and Detectron2 Fine-Tuning Pipeline for LeafMachine2's (LM2)
    Plant Component Detector (PCD) using PointRend Instance Segmentation.

Key Features & Specifications:
    1. Custom COCO Dataset Ingestion:
       - Uses `detectron2.data.datasets.register_coco_instances()` to register
         the COCO 1.0 JSON dataset generated by `prepare_lm2_dataset.py`.
       - Targets 2 supervised PCD component classes:
           * Category 1: 'ideal_leaf'   (pristine basal leaves with intact petiole)
           * Category 2: 'partial_leaf' (occluded, damaged, or overlapping basal blades)
       - Intentionally ignores cauline foliage and non-target structures as background noise.

    2. PointRend High-Resolution Boundary Architecture:
       - Instantiates Mask R-CNN with PointRend head (R-50 / R-101 FPN backbone).
       - Point sampling subdivision refines complex dissected and crenate leaf margins.

    3. Anti-Catastrophic Forgetting via Backbone Freezing:
       - Freezes early ResNet/FPN stages (stem + res2 by default, configurable)
         to preserve general botanical visual primitives while adapting the
         ROI heads and PointRend segmentation MLP to Asteraceae / Packera morphology.

    4. Standardized Hyperparameters & Optimization:
       - Base Learning Rate: 0.0001 (1e-4) with warm-up and multi-step decay.
       - Iterations: Exactly 2,500 iterations (configurable via CLI).
       - Optimizer: WarmupMultiStepLR with SGD / AdamW option.

    5. Production Weight Export & LM2 Interoperability:
       - Initializes from default LeafMachine2 `LeafPriority.pth` / `model_final.pth`.
       - Exports final trained weights as `Packera_LeafPriority.pth`.
       - Writes accompanying `cfg_output.yaml` and `metadata.json` for seamless
         drop-in execution with LeafMachine2's `Detector_LM2` inference module.

Usage Examples:
    # 1. Standard fine-tuning (2,500 iterations, LR=0.0001, output Packera_LeafPriority.pth):
    python scripts/vision/train_lm2_pointrend.py \\
        --coco-json LM2_Project/Data/annotations/coco_pcd_packera.json \\
        --images-dir LM2_Project/Data/images \\
        --output-dir LM2_Project/Data/output/pcd_training \\
        --iterations 2500 \\
        --lr 0.0001

    # 2. Dry run mode to audit config, layer freeze status, and dataset registration:
    python scripts/vision/train_lm2_pointrend.py --dry-run

    # 3. Fine-tuning with train/val split and validation evaluation:
    python scripts/vision/train_lm2_pointrend.py \\
        --coco-json LM2_Project/Data/annotations/coco_pcd_packera_train.json \\
        --val-coco-json LM2_Project/Data/annotations/coco_pcd_packera_val.json \\
        --weights models/LeafPriority.pth
===============================================================================
"""

import argparse
import json
import logging
import os
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

# Disable uninitialized wandb tracking unless explicitly requested
if "--wandb" not in sys.argv:
    os.environ.setdefault("WANDB_MODE", "disabled")
    os.environ.setdefault("WANDB_SILENT", "true")

# ===============================================================================
# ENVIRONMENT & DYNAMIC PATH RESOLUTION FOR LEAFMACHINE2 / DETECTRON2
# ===============================================================================

def setup_environment_paths() -> Path:
    """
    Ensure LeafMachine2 and bundled Detectron2 / PointRend packages are on sys.path.
    If required dependencies (e.g. fvcore, iopath) are missing in the current Python
    environment, automatically re-execute with the dedicated .venv_LM2 interpreter.
    """
    script_path = Path(__file__).resolve()
    # Search upwards for repo root
    project_root = script_path.parents[2] if len(script_path.parents) >= 3 else script_path.parent
    for parent in [script_path.parent] + list(script_path.parents):
        if (parent / "LeafMachine2").exists() or (parent / ".git").exists() or (parent / "LM2_Project").exists():
            project_root = parent
            break

    # 1. Check if dedicated LeafMachine2 virtual environment exists and is needed
    lm2_prefix = project_root / ".venv_LM2"
    lm2_python = lm2_prefix / "bin" / "python"
    if not lm2_python.exists():
        lm2_python = lm2_prefix / "bin" / "python3"

    try:
        import fvcore
        import iopath
    except ImportError:
        # If running from another venv (e.g., .venv) and .venv_LM2 is available, auto re-exec
        if lm2_python.exists() and lm2_prefix.exists():
            if Path(sys.prefix).resolve() != lm2_prefix.resolve() and os.environ.get("LM2_AUTO_REEXEC") != "1":
                env = dict(os.environ)
                env["LM2_AUTO_REEXEC"] = "1"
                env["VIRTUAL_ENV"] = str(lm2_prefix)
                env["PATH"] = str(lm2_prefix / "bin") + ":" + env.get("PATH", "")
                os.execve(str(lm2_python), [str(lm2_python)] + sys.argv, env)

    lm2_root = project_root / "LeafMachine2"
    lm2_pkg = lm2_root / "leafmachine2"
    lm2_detectron = lm2_pkg / "segmentation" / "detectron2"

    paths_to_add = [
        str(project_root),
        str(lm2_root),
        str(lm2_pkg),
        str(lm2_detectron),
    ]

    for p in paths_to_add:
        if os.path.exists(p) and p not in sys.path:
            sys.path.insert(0, p)

    return project_root


PROJECT_ROOT = setup_environment_paths()

# Third-party imports with clear diagnostics
try:
    import torch
    import torch.nn as nn
except ImportError as err:
    print(f"[FATAL] PyTorch is required but not installed: {err}", file=sys.stderr)
    sys.exit(1)

try:
    import detectron2
    from detectron2.checkpoint import DetectionCheckpointer
    from detectron2.config import CfgNode, get_cfg
    from detectron2.data import DatasetCatalog, MetadataCatalog, build_detection_train_loader, build_detection_test_loader
    from detectron2.data.datasets import register_coco_instances
    from detectron2.engine import DefaultTrainer, default_setup, hooks
    from detectron2.evaluation import COCOEvaluator, inference_on_dataset
    from detectron2.modeling import build_model
    from detectron2.projects import point_rend
    from detectron2.utils.logger import setup_logger as d2_setup_logger
except ImportError as err:
    print(
        f"[FATAL] Detectron2 / PointRend could not be imported: {err}\n"
        f"Ensure you are running within the dedicated virtual environment (.venv_LM2):\n"
        f"  source .venv_LM2/bin/activate\n"
        f"or execute directly via:\n"
        f"  .venv_LM2/bin/python scripts/vision/train_lm2_pointrend.py ...",
        file=sys.stderr,
    )
    sys.exit(1)


# ===============================================================================
# CONSTANTS & METADATA
# ===============================================================================

TARGET_CLASSES: List[str] = ["ideal_leaf", "partial_leaf"]
CLASS_COLORS: List[List[int]] = [[0, 255, 46], [255, 173, 0]]  # Green for ideal, Orange for partial
NUM_CLASSES: int = len(TARGET_CLASSES)

DEFAULT_COCO_JSON = PROJECT_ROOT / "LM2_Project" / "Data" / "annotations" / "coco_pcd_packera.json"
DEFAULT_IMAGES_DIR = PROJECT_ROOT / "LM2_Project" / "Data" / "images"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "LM2_Project" / "Data" / "output" / "pcd_training"
DEFAULT_OUTPUT_WEIGHTS_NAME = "Packera_LeafPriority.pth"


# ===============================================================================
# LOGGING SETUP
# ===============================================================================

def setup_logging(output_dir: Optional[Path] = None, verbose: bool = False) -> logging.Logger:
    """Configure structured logging to console and optional log file."""
    log_level = logging.DEBUG if verbose else logging.INFO
    logger = logging.getLogger("LM2_PCD_Train")
    logger.setLevel(log_level)

    # Avoid duplicate handlers if re-initialized
    if not logger.handlers:
        formatter = logging.Formatter(
            fmt="[%(asctime)s] [%(levelname)s] %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )

        ch = logging.StreamHandler(sys.stdout)
        ch.setLevel(log_level)
        ch.setFormatter(formatter)
        logger.addHandler(ch)

        if output_dir:
            output_dir.mkdir(parents=True, exist_ok=True)
            fh = logging.FileHandler(output_dir / "pcd_training.log", encoding="utf-8")
            fh.setLevel(log_level)
            fh.setFormatter(formatter)
            logger.addHandler(fh)

    # Also configure detectron2 internal logger
    d2_setup_logger(output=str(output_dir) if output_dir else None, name="detectron2")
    return logger


# ===============================================================================
# DATASET REGISTRATION & VERIFICATION
# ===============================================================================

def register_pcd_coco_dataset(
    dataset_name: str,
    coco_json_path: Path,
    images_dir: Path,
    logger: logging.Logger,
) -> bool:
    """
    Safely registers a COCO 1.0 JSON dataset into Detectron2's DatasetCatalog
    and configures MetadataCatalog with target class names and colors.
    """
    if not coco_json_path.exists():
        logger.error(f"COCO JSON dataset file not found: {coco_json_path.resolve()}")
        return False

    if not images_dir.exists():
        logger.warning(f"Images directory not found at {images_dir.resolve()}. Checking fallback search paths...")
        # Fallback to data/raw_vouchers if LM2 symlinks not yet generated
        fallback_raw = PROJECT_ROOT / "data" / "raw_vouchers"
        if fallback_raw.exists():
            images_dir = fallback_raw
            logger.info(f"Using fallback images directory: {images_dir.resolve()}")
        else:
            logger.error(f"Could not locate image directory: {images_dir.resolve()}")
            return False

    # Check if already registered (clean re-registration)
    if dataset_name in DatasetCatalog.list():
        logger.debug(f"Dataset '{dataset_name}' already registered in catalog. Using existing entry.")
        return True

    register_coco_instances(
        name=dataset_name,
        metadata={},
        json_file=str(coco_json_path.resolve()),
        image_root=str(images_dir.resolve()),
    )

    # Set metadata for visualizers and evaluation
    MetadataCatalog.get(dataset_name).set(
        thing_classes=TARGET_CLASSES,
        thing_colors=CLASS_COLORS,
        json_file=str(coco_json_path.resolve()),
        image_root=str(images_dir.resolve()),
        evaluator_type="coco",
    )

    try:
        dataset_dicts = DatasetCatalog.get(dataset_name)
        total_annotations = sum(len(d.get("annotations", [])) for d in dataset_dicts)
        logger.info(
            f"Successfully registered dataset '{dataset_name}': "
            f"{len(dataset_dicts)} images, {total_annotations} annotations."
        )
        return True
    except Exception as e:
        logger.error(f"Failed to load registered dataset '{dataset_name}': {e}")
        return False


# ===============================================================================
# WEIGHT INITIALIZATION RESOLVER
# ===============================================================================

def resolve_initial_weights(
    custom_weights_path: Optional[Union[str, Path]],
    project_root: Path,
    logger: logging.Logger,
) -> Tuple[str, str]:
    """
    Resolves the initial checkpoint weights for LeafMachine2 PCD fine-tuning.
    Checks candidate locations in priority order:
      1. User-supplied CLI argument (--weights)
      2. models/LeafPriority.pth or models/checkpoints/LeafPriority.pth
      3. LeafMachine2 embedded PCD weights (PLANT_LeafPriority / Group3)
      4. Detectron2 PointRend COCO model zoo baseline URL
    """
    candidates: List[Tuple[str, Path]] = []

    if custom_weights_path:
        p = Path(custom_weights_path)
        candidates.append(("User-Specified Path", p if p.is_absolute() else project_root / p))

    # Standard model cache locations
    candidates.extend([
        ("Project Models Directory (pth)", project_root / "models" / "LeafPriority.pth"),
        ("Project Models Checkpoints (pth)", project_root / "models" / "checkpoints" / "LeafPriority.pth"),
        ("Project Models Directory (pt)", project_root / "models" / "LeafPriority.pt"),
        (
            "LeafMachine2 Native Group3 PCD Segmentation Model (model_final.pth)",
            project_root
            / "LeafMachine2"
            / "leafmachine2"
            / "segmentation"
            / "models"
            / "Group3_Dataset_100000_Iter_1176PTS_512Batch_smooth_l1_LR00025_BGR"
            / "model_final.pth",
        ),
        (
            "LeafMachine2 Native GroupB PCD Segmentation Model (model_final.pth)",
            project_root
            / "LeafMachine2"
            / "leafmachine2"
            / "segmentation"
            / "models"
            / "GroupB_Dataset_100000_Iter_1176PTS_512Batch_smooth_l1_LR00025_BGR"
            / "model_final.pth",
        ),
        (
            "LeafMachine2 Component Detector Weights (LeafPriority.pt)",
            project_root
            / "LeafMachine2"
            / "leafmachine2"
            / "component_detector"
            / "runs"
            / "train"
            / "Plant_Detector"
            / "PLANT_LeafPriority"
            / "PLANT_LeafPriority"
            / "weights"
            / "LeafPriority.pt",
        ),
    ])

    for source_desc, cand_path in candidates:
        if cand_path.exists() and cand_path.is_file() and cand_path.stat().st_size > 1024:
            logger.info(f"Found initial PCD weights [{source_desc}]: {cand_path.resolve()}")
            return str(cand_path.resolve()), source_desc

    # Fallback to Detectron2 PointRend standard COCO checkpoint URL
    zoo_url = "detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_edd263.pkl"
    logger.warning(
        f"No local LeafPriority weights found on disk. Falling back to Detectron2 PointRend baseline: {zoo_url}"
    )
    return zoo_url, "Detectron2 Model Zoo PointRend Baseline"


# ===============================================================================
# DETECTRON2 & POINTREND CONFIGURATION BUILDER
# ===============================================================================

def build_pointrend_config(args: argparse.Namespace, logger: logging.Logger) -> CfgNode:
    """
    Construct and validate the Detectron2 CfgNode for PointRend instance segmentation
    with backbone layer freezing, class configuration, and fine-tuning learning rate.
    """
    cfg = get_cfg()
    point_rend.add_pointrend_config(cfg)

    # Locate base PointRend R-50 FPN config file inside LeafMachine2
    lm2_detectron = PROJECT_ROOT / "LeafMachine2" / "leafmachine2" / "segmentation" / "detectron2"
    base_pointrend_yaml = (
        lm2_detectron
        / "projects"
        / "PointRend"
        / "configs"
        / "InstanceSegmentation"
        / "pointrend_rcnn_R_50_FPN_3x_coco.yaml"
    )

    if base_pointrend_yaml.exists():
        cfg.merge_from_file(str(base_pointrend_yaml.resolve()))
        logger.info(f"Merged base PointRend config from: {base_pointrend_yaml.name}")
    else:
        # Programmatic configuration fallback
        logger.info("Configuring PointRend architecture programmatically...")
        cfg.MODEL.META_ARCHITECTURE = "GeneralizedRCNN"
        cfg.MODEL.BACKBONE.NAME = "build_resnet_fpn_backbone"
        cfg.MODEL.RESNETS.OUT_FEATURES = ["res2", "res3", "res4", "res5"]
        cfg.MODEL.FPN.IN_FEATURES = ["res2", "res3", "res4", "res5"]
        cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[32], [64], [128], [256], [512]]
        cfg.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.5, 1.0, 2.0]]
        cfg.MODEL.RPN.IN_FEATURES = ["p2", "p3", "p4", "p5", "p6"]
        cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN = 2000
        cfg.MODEL.RPN.PRE_NMS_TOPK_TEST = 1000
        cfg.MODEL.RPN.POST_NMS_TOPK_TRAIN = 1000
        cfg.MODEL.RPN.POST_NMS_TOPK_TEST = 1000
        cfg.MODEL.ROI_HEADS.NAME = "StandardROIHeads"
        cfg.MODEL.ROI_HEADS.IN_FEATURES = ["p2", "p3", "p4", "p5"]
        cfg.MODEL.ROI_BOX_HEAD.NAME = "FastRCNNConvFCHead"
        cfg.MODEL.ROI_BOX_HEAD.NUM_FC = 2
        cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7
        cfg.MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True
        cfg.MODEL.MASK_ON = True
        cfg.MODEL.ROI_MASK_HEAD.NAME = "PointRendMaskHead"
        cfg.MODEL.ROI_MASK_HEAD.NUM_CONV = 4
        cfg.MODEL.ROI_MASK_HEAD.NUM_FC = 2
        cfg.MODEL.ROI_MASK_HEAD.FC_DIM = 1024
        cfg.MODEL.ROI_MASK_HEAD.OUTPUT_SIDE_RESOLUTION = 7
        cfg.MODEL.ROI_MASK_HEAD.IN_FEATURES = ["p2"]
        cfg.MODEL.ROI_MASK_HEAD.POINT_HEAD_ON = True
        cfg.MODEL.ROI_MASK_HEAD.POOLER_TYPE = ""
        cfg.MODEL.POINT_HEAD.NAME = "StandardPointHead"
        cfg.MODEL.POINT_HEAD.IN_FEATURES = ["p2"]
        cfg.MODEL.POINT_HEAD.FC_DIM = 256
        cfg.MODEL.POINT_HEAD.NUM_FC = 3

    # Dataset bindings
    cfg.DATASETS.TRAIN = (args.train_dataset_name,)
    if args.val_dataset_name:
        cfg.DATASETS.TEST = (args.val_dataset_name,)
    else:
        cfg.DATASETS.TEST = ()

    # Target class configuration (ideal_leaf, partial_leaf)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = NUM_CLASSES
    cfg.MODEL.POINT_HEAD.NUM_CLASSES = NUM_CLASSES
    cfg.INPUT.MASK_FORMAT = "bitmask"

    # Anti-Catastrophic Forgetting: Backbone Freezing
    # FREEZE_AT = 2 freezes Stem (conv1/bn1) and res2 stage
    # FREEZE_AT = 3 freezes Stem + res2 + res3
    cfg.MODEL.BACKBONE.FREEZE_AT = int(args.freeze_at)

    # Initial weights initialization
    weights_path, _ = resolve_initial_weights(args.weights, PROJECT_ROOT, logger)
    cfg.MODEL.WEIGHTS = weights_path

    # Solver & Optimizer Hyperparameters
    cfg.SOLVER.BASE_LR = float(args.lr)
    cfg.SOLVER.MAX_ITER = int(args.iterations)
    cfg.SOLVER.IMS_PER_BATCH = int(args.batch_size)
    cfg.DATALOADER.NUM_WORKERS = int(args.num_workers)

    # Multi-step learning rate decay schedule (default: decay at 60% and 80% of MAX_ITER)
    step1 = int(round(cfg.SOLVER.MAX_ITER * 0.60))
    step2 = int(round(cfg.SOLVER.MAX_ITER * 0.80))
    cfg.SOLVER.STEPS = (step1, step2)
    cfg.SOLVER.GAMMA = 0.1
    cfg.SOLVER.WARMUP_FACTOR = 0.001
    cfg.SOLVER.WARMUP_ITERS = min(100, int(cfg.SOLVER.MAX_ITER * 0.05))
    cfg.SOLVER.WARMUP_METHOD = "linear"
    cfg.SOLVER.CHECKPOINT_PERIOD = int(args.checkpoint_period)

    # Evaluation frequency
    cfg.TEST.EVAL_PERIOD = int(args.eval_period) if args.val_dataset_name else 0

    # Device configuration
    if args.cpu or not torch.cuda.is_available():
        cfg.MODEL.DEVICE = "cpu"
    else:
        cfg.MODEL.DEVICE = "cuda"

    # Destination directory for logs, checkpoints, and weights
    cfg.OUTPUT_DIR = str(Path(args.output_dir).resolve())
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

    return cfg


# ===============================================================================
# BACKBONE & PARAMETER AUDITING
# ===============================================================================

def audit_and_verify_model_layers(model: nn.Module, freeze_at: int, logger: logging.Logger) -> Dict[str, Any]:
    """
    Audits model parameters, verifying which layers are frozen vs trainable.
    Logs parameter statistics and ensures early ResNet stages have requires_grad=False.
    """
    total_params = 0
    trainable_params = 0
    frozen_params = 0

    frozen_layer_groups: List[str] = []
    trainable_layer_groups: List[str] = []

    for name, param in model.named_parameters():
        num_el = param.numel()
        total_params += num_el
        if param.requires_grad:
            trainable_params += num_el
            # Summarize group names
            grp = ".".join(name.split(".")[:2])
            if grp not in trainable_layer_groups:
                trainable_layer_groups.append(grp)
        else:
            frozen_params += num_el
            grp = ".".join(name.split(".")[:2])
            if grp not in frozen_layer_groups:
                frozen_layer_groups.append(grp)

    trainable_pct = (trainable_params / total_params * 100.0) if total_params > 0 else 0.0
    frozen_pct = (frozen_params / total_params * 100.0) if total_params > 0 else 0.0

    logger.info("=================================================================")
    logger.info("          MODEL PARAMETER & LAYER FREEZING AUDIT                 ")
    logger.info("=================================================================")
    logger.info(f" Backbone FREEZE_AT Level : {freeze_at} (0=None, 1=Stem, 2=Stem+Res2, 3=Stem+Res2+Res3)")
    logger.info(f" Total Parameters         : {total_params:,}")
    logger.info(f" Trainable Parameters     : {trainable_params:,} ({trainable_pct:.2f}%)")
    logger.info(f" Frozen Parameters        : {frozen_params:,} ({frozen_pct:.2f}%)")
    logger.info(f" Frozen Layer Groups      : {', '.join(frozen_layer_groups) if frozen_layer_groups else '(None)'}")
    logger.info(f" Trainable Layer Groups   : {', '.join(trainable_layer_groups)}")
    logger.info("=================================================================")

    return {
        "total_params": total_params,
        "trainable_params": trainable_params,
        "frozen_params": frozen_params,
        "trainable_pct": trainable_pct,
        "frozen_pct": frozen_pct,
        "freeze_at": freeze_at,
    }


# ===============================================================================
# CUSTOM DETECTRON2 TRAINER WITH COCO EVALUATION
# ===============================================================================

class PCDPointRendTrainer(DefaultTrainer):
    """
    Customized Detectron2 Trainer configured for LeafMachine2 PCD fine-tuning.
    Provides COCO instance segmentation evaluation and progress tracking.
    """

    @classmethod
    def build_evaluator(cls, cfg: CfgNode, dataset_name: str, output_folder: Optional[str] = None):
        """Build COCO instance evaluator for validation dataset."""
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "coco_evaluation")
        os.makedirs(output_folder, exist_ok=True)
        return COCOEvaluator(dataset_name, output_dir=output_folder)


# ===============================================================================
# LEAFMACHINE2 METADATA & CONFIG EXPORT
# ===============================================================================

def export_lm2_artifacts(
    cfg: CfgNode,
    output_dir: Path,
    weights_name: str,
    logger: logging.Logger,
) -> Tuple[Path, Path, Path]:
    """
    Exports the final fine-tuned model checkpoint as `Packera_LeafPriority.pth`
    along with `cfg_output.yaml` and `metadata.json` for direct use in LeafMachine2.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Output weights file (Packera_LeafPriority.pth)
    model_final_path = output_dir / "model_final.pth"
    target_weights_path = output_dir / weights_name

    if model_final_path.exists():
        shutil.copyfile(model_final_path, target_weights_path)
        logger.info(f"Exported primary PCD weights to: {target_weights_path.resolve()}")
    else:
        # Check for checkpoint models
        ckpts = sorted(list(output_dir.glob("model_*.pth")))
        if ckpts:
            latest_ckpt = ckpts[-1]
            shutil.copyfile(latest_ckpt, target_weights_path)
            logger.info(f"Exported checkpoint [{latest_ckpt.name}] as: {target_weights_path.resolve()}")
        else:
            logger.warning(f"No checkpoint file found in {output_dir.resolve()} to rename to {weights_name}.")

    # Also copy to project models/ directory if accessible
    models_dir = PROJECT_ROOT / "models"
    if models_dir.exists() and target_weights_path.exists():
        dest_model = models_dir / weights_name
        try:
            shutil.copyfile(target_weights_path, dest_model)
            logger.info(f"Mirrored production weights to: {dest_model.resolve()}")
        except Exception as e:
            logger.debug(f"Could not mirror weights to models/: {e}")

    # 2. Export cfg_output.yaml
    cfg_output_path = output_dir / "cfg_output.yaml"
    with open(cfg_output_path, "w", encoding="utf-8") as f:
        f.write(cfg.dump())
    logger.info(f"Exported Detectron2 config to: {cfg_output_path.resolve()}")

    # 3. Export metadata.json
    metadata_path = output_dir / "metadata.json"
    metadata_content = {
        "thing_classes": TARGET_CLASSES,
        "thing_colors": CLASS_COLORS,
        "num_classes": NUM_CLASSES,
        "dataset_name": cfg.DATASETS.TRAIN[0] if cfg.DATASETS.TRAIN else "pcd_packera_train",
        "date_trained": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "base_model": "PointRend_R_50_FPN",
        "weights_file": weights_name,
        "iterations": cfg.SOLVER.MAX_ITER,
        "base_lr": cfg.SOLVER.BASE_LR,
        "taxonomic_scope": "Packera dubia complex (basal rosette blade & petiole segmentation)",
    }
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata_content, f, indent=2)
    logger.info(f"Exported LM2 detector metadata to: {metadata_path.resolve()}")

    return target_weights_path, cfg_output_path, metadata_path


# ===============================================================================
# CLI ARGUMENT PARSER & ORCHESTRATION
# ===============================================================================

def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Fine-tune LeafMachine2 Plant Component Detector (PointRend) for Packera dubia.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Dataset Arguments
    data_group = parser.add_argument_group("Dataset Configuration")
    data_group.add_argument(
        "--coco-json",
        "-c",
        type=Path,
        default=DEFAULT_COCO_JSON,
        help="Path to training COCO 1.0 JSON dataset produced by prepare_lm2_dataset.py.",
    )
    data_group.add_argument(
        "--val-coco-json",
        type=Path,
        default=None,
        help="Optional path to validation COCO 1.0 JSON dataset.",
    )
    data_group.add_argument(
        "--images-dir",
        "-i",
        type=Path,
        default=DEFAULT_IMAGES_DIR,
        help="Directory containing herbarium sheet images (or symlinks).",
    )
    data_group.add_argument(
        "--train-dataset-name",
        type=str,
        default="lm2_pcd_packera_train",
        help="Detectron2 DatasetCatalog registration name for training data.",
    )
    data_group.add_argument(
        "--val-dataset-name",
        type=str,
        default="lm2_pcd_packera_val",
        help="Detectron2 DatasetCatalog registration name for validation data.",
    )

    # Training & Fine-Tuning Hyperparameters
    train_group = parser.add_argument_group("Training & Optimization Hyperparameters")
    train_group.add_argument(
        "--iterations",
        "-n",
        type=int,
        default=2500,
        help="Total training iterations for fine-tuning.",
    )
    train_group.add_argument(
        "--lr",
        type=float,
        default=0.0001,
        help="Base learning rate (default: 0.0001 / 1e-4).",
    )
    train_group.add_argument(
        "--batch-size",
        "-b",
        type=int,
        default=2,
        help="Total images per batch across GPUs.",
    )
    train_group.add_argument(
        "--freeze-at",
        type=int,
        default=2,
        help="ResNet backbone freeze stage (1: stem, 2: stem+res2, 3: stem+res2+res3).",
    )
    train_group.add_argument(
        "--weights",
        "-w",
        type=str,
        default=None,
        help="Initial model weights path (defaults to LeafPriority.pth / Group3 model).",
    )
    train_group.add_argument(
        "--num-workers",
        type=int,
        default=4,
        help="DataLoader worker subprocesses.",
    )
    train_group.add_argument(
        "--checkpoint-period",
        type=int,
        default=500,
        help="Checkpoint saving interval in iterations.",
    )
    train_group.add_argument(
        "--eval-period",
        type=int,
        default=500,
        help="Validation evaluation interval in iterations.",
    )

    # Output & Execution Controls
    output_group = parser.add_argument_group("Output & Execution Controls")
    output_group.add_argument(
        "--output-dir",
        "-o",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to store training logs, checkpoints, and final model weights.",
    )
    output_group.add_argument(
        "--output-name",
        type=str,
        default=DEFAULT_OUTPUT_WEIGHTS_NAME,
        help="Name of final exported weights file (e.g., Packera_LeafPriority.pth).",
    )
    output_group.add_argument(
        "--resume",
        action="store_true",
        help="Resume training from latest checkpoint in output-dir.",
    )
    output_group.add_argument(
        "--eval-only",
        action="store_true",
        help="Perform evaluation on validation set only without training.",
    )
    output_group.add_argument(
        "--dry-run",
        action="store_true",
        help="Perform configuration setup, dataset registration, and layer audit without training.",
    )
    output_group.add_argument(
        "--cpu",
        action="store_true",
        help="Force CPU execution even if CUDA GPU is available.",
    )
    output_group.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable detailed debug logging.",
    )

    return parser.parse_args()


# ===============================================================================
# MAIN PIPELINE ENTRYPOINT
# ===============================================================================

def main() -> int:
    """Orchestrates LeafMachine2 PCD PointRend fine-tuning pipeline."""
    args = parse_arguments()
    logger = setup_logging(output_dir=args.output_dir, verbose=args.verbose)

    logger.info("=================================================================")
    logger.info(" LeafMachine2 PCD PointRend Fine-Tuning Pipeline (Packera dubia)")
    logger.info("=================================================================")
    logger.info(f" Execution Timestamp   : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info(f" PyTorch Version       : {torch.__version__} (CUDA Available: {torch.cuda.is_available()})")
    logger.info(f" Detectron2 Version    : {detectron2.__version__}")
    if torch.cuda.is_available() and not args.cpu:
        logger.info(f" Active GPU Device     : {torch.cuda.get_device_name(0)}")
    logger.info(f" Training COCO JSON    : {args.coco_json.resolve()}")
    logger.info(f" Voucher Images Root   : {args.images_dir.resolve()}")
    logger.info(f" Target Output Dir     : {args.output_dir.resolve()}")
    logger.info(f" Target Weights Name   : {args.output_name}")
    logger.info(f" Base Learning Rate    : {args.lr}")
    logger.info(f" Total Iterations      : {args.iterations}")
    logger.info(f" Backbone Freeze Level : FREEZE_AT = {args.freeze_at}")
    logger.info(f" Target PCD Classes    : {TARGET_CLASSES} (Category IDs: 1, 2)")
    logger.info("=================================================================\n")

    # 1. Register Training Dataset
    train_success = register_pcd_coco_dataset(
        dataset_name=args.train_dataset_name,
        coco_json_path=args.coco_json,
        images_dir=args.images_dir,
        logger=logger,
    )
    if not train_success:
        logger.error("Failed to register training COCO dataset. Aborting fine-tuning.")
        return 1

    # 2. Register Validation Dataset (if provided)
    if args.val_coco_json and args.val_coco_json.exists():
        register_pcd_coco_dataset(
            dataset_name=args.val_dataset_name,
            coco_json_path=args.val_coco_json,
            images_dir=args.images_dir,
            logger=logger,
        )
    else:
        args.val_dataset_name = None

    # 3. Build PointRend Configuration
    cfg = build_pointrend_config(args, logger)

    # 4. Instantiate Model & Audit Layer Freezing
    model = build_model(cfg)
    audit_stats = audit_and_verify_model_layers(model, cfg.MODEL.BACKBONE.FREEZE_AT, logger)

    if args.dry_run:
        logger.info("\n[DRY RUN] Configuration and model layer audit completed successfully.")
        logger.info(f"[DRY RUN] Weights to load on run: {cfg.MODEL.WEIGHTS}")
        logger.info(f"[DRY RUN] Output weights destination: {(args.output_dir / args.output_name).resolve()}")
        logger.info("Exiting without executing training loop as requested (--dry-run).")
        return 0

    # 5. Evaluation Only Mode
    if args.eval_only:
        if not args.val_dataset_name:
            logger.error("Evaluation mode requires a valid validation dataset (--val-coco-json).")
            return 1
        logger.info("Running evaluation on validation dataset...")
        DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
            cfg.MODEL.WEIGHTS, resume=args.resume
        )
        evaluator = PCDPointRendTrainer.build_evaluator(cfg, args.val_dataset_name)
        val_loader = build_detection_test_loader(cfg, args.val_dataset_name)
        results = inference_on_dataset(model, val_loader, evaluator)
        logger.info(f"Evaluation Results:\n{json.dumps(results, indent=2)}")
        return 0

    # 6. Initialize Trainer & Execute Fine-Tuning Loop
    logger.info("\nInitializing PCDPointRendTrainer and loading initial weights...")
    trainer = PCDPointRendTrainer(cfg)
    trainer.resume_or_load(resume=args.resume)

    start_time = time.time()
    logger.info(f"Beginning fine-tuning for exactly {cfg.SOLVER.MAX_ITER} iterations...")

    try:
        trainer.train()
    except Exception as e:
        logger.error(f"Error during training execution: {e}", exc_info=True)
        return 1

    elapsed_time = time.time() - start_time
    logger.info(f"Training completed in {elapsed_time/60.0:.2f} minutes ({elapsed_time:.1f} seconds).")

    # 7. Post-Training Artifacts & Weight Export
    target_weights, cfg_yaml, metadata = export_lm2_artifacts(
        cfg=cfg,
        output_dir=args.output_dir,
        weights_name=args.output_name,
        logger=logger,
    )

    logger.info("=================================================================")
    logger.info("       LEAFMACHINE2 PCD POINTREND FINE-TUNING SUMMARY            ")
    logger.info("=================================================================")
    logger.info(f" Final Model Weights Exported : {target_weights.resolve()}")
    logger.info(f" Detectron2 Config Exported   : {cfg_yaml.resolve()}")
    logger.info(f" Detector Metadata Exported   : {metadata.resolve()}")
    logger.info(f" Total Training Iterations    : {cfg.SOLVER.MAX_ITER}")
    logger.info(f" Target Supervised Categories : {TARGET_CLASSES}")
    logger.info(f" Status                       : READY FOR LEAFMACHINE2 INFERENCE")
    logger.info("=================================================================\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
